### ISSUE TITLE
Affix giving a wrong top position to the affixed element

### ISSUE THREAD

**Issue by ricardosimoes** [eddiemf/vue-affix#10]
Hello. 

I started using this plugin and I detected an awkward behavior. When the element gets fixed it gets a wrong top position that is causing a jump. Check this URL with a video to get a clear view of the behavior: https://www.screencast.com/t/PNmzixNOHL1w

I tried different offsets but didn't fix the issue. Can you help me clearing out this?

Thanks

**Comment by eddiemf** [comment]
Can you provide me a fiddle reproducing this unexpected behavior? I think it might be something with the style of the element you're affixing, or the element it self (maybe try affixing the parent or children). I had a lot of these problems when testing in early development, but fixed all that I could reproduce, so it won't be that easy without a code reproducing it. Thanks :)

**Comment by eddiemf** [comment]
Ok, this seems to happen when you have a margin in your relative element, because the threshold to affix the element is calculated based on the relative element offset top, so if you have any margin on it, the affix will be applied after the margin value, not when it reaches the top of the margin, which causes a jump. You should try to not use margins in the relative element. If you need some spacing use padding instead or keep playing with values and helper divs.
