### ISSUE TITLE
Calling affix after resizing the document

### ISSUE THREAD

**Issue by DJanoskova** [eddiemf/vue-affix#11]
Hello, I love your plugin!

Is there any way to call the affix function?

For example - I resize my document and I recalculate my affix element width and I wish to call the affix to render again. Or I change my data and I wish to change the dimensions of the affix element.

Does it have any callable function to refresh it?

**Comment by eddiemf** [comment]
Hey, thanks for the compassion!

Why do you need that? Does it break when you set a different width? Because the demo works out of the box when you resize the page. The width gets changed in media queries and nothing breaks.

If you could show me your working code in a fiddle I could check if there's something I can do :)

**Comment by eddiemf** [comment]
I'm closing this since there was no reply for a long time, feel free to open again in case you still need help :)

**Comment by plakhin** [comment]
@DJanoskova did you find a way to "rerender" affix element?

**Comment by simboonlong** [comment]
You can define a ref to your affix element:

<affix class="sidebar-menu" relative-element-selector="#example-content" style="width: 300px" ref="sidebar-menu"></affix>

Then in your vue methods function, call:

this.$refs['sidebar-menu'].setAffix()
this.$refs['sidebar-menu'].lastState = 'affix'

Refer to the source code https://github.com/eddiemf/vue-affix/blob/master/src/affix.vue for the other available methods...
