### ISSUE TITLE
Support request for FireFox

### ISSUE THREAD

**Issue by wataruoguchi** [eddiemf/vue-affix#14]
Hi,

Firstly, thank you for making such a nice plug-in. I've been playing with it and really like it.

The question is that if this plug-in officially supports FireFox(FF). I opened [the example page](https://eddiemf.github.io/vue-affix/examples/example-1.html) in FF. I realized "Scroll Affix sidebar" doesn't look like how you intended. As well as the highlighting in "Affix sidebar".

macOS version 10.13.3
FF version 58.0.2

Thanks,

**Comment by eddiemf** [comment]
Hey, @wataruoguchi! Thanks for the compassion!

I've tested the demo page in the exact same environment as you're running and the "Scroll affix sidebar" is looking perfectly good, could you show me how it looks for you?

As for the highlighting in the left sidebar, I see that it's really not working as intended, but that's a concern of `vue-scrollactive` (https://github.com/eddiemf/vue-scrollactive) which is another plugin maintained by me. 

I'll take a look to see what's making it misbehave and hope to hear from you about the "scroll affix sidebar", because it might be something else that's causing the bug.

Thanks for pointing these out!
