### ISSUE TITLE
Local install support.

### ISSUE THREAD

**Issue by shalldie** [eddiemf/vue-affix#18]
hi,

I find it that, the `vue-affix` only could be `global install` , there's no way to `local install` , right?

I want to use it like this, in a '.vue':

```js
import VueAffix from 'vue-affix';

export default {
    components: {
        'vue-affix': VueAffix
    }
};
```

Can u add the support for `local install`?

**Comment by eddiemf** [comment]
That's because this is treated as a plugin, but I'll see the possibility of providing it as a component in next release :)

Thanks for the feedback

**Comment by zamarawka** [comment]
@eddiemf really need this.

**Comment by eddiemf** [comment]
Hello guys, sorry for the delay on this. I've just released a new version where you can import the component locally instead of as a plugin.

Instead of importing the default module, import the `{ Affix }` object as below:

`import { Affix } from 'vue-affix';`

This is only temporary until I release the next major, which shall turn it into a component instead of a plugin. 
Soon I'll add the changes to the docs.
